---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-secret 
  namespace: default
spec:
  encryptedData:
    TOKEN: AgAU2hQsT2y0+O7HHBuajYrlj/aZ+2UXJOimy4KYaU1NgCd4d99EZN6UwoD+uN/gw9Qc6wGjns2Ext2AtW5Lew25sqMNA91tHJ4hLBT2I4lsGAQE73XHS8lLFg7nWplHH4HawAX0TmUUGwqXSExWJ3LVLz2t3saWl1BBY7qKNutEvZxBux6bctI+0NM0otZ2ypBx2nSJIMQF4JWRebuKCc2t1mAysgAIt3o663+hPv8uGftkxfnKzhp8asMhKT9//T2Ntptp8v811i/4BOM5npharIXR51BDHrc4HJXB0Sxs7EX93nNr88HXe3yVDLPn4MTa38Wvedie4ulH0ATw0FKcwP7mSaeGZ2lc1UAVT/doqhVEX+n8RbE2cX4uxwidgbatVxom1kmDSGyBycfj2QjKLYNkeUJOPDu7mKoNW/p60bLmPAyt+TNwH+KzTlptExGX+XfpnPR4MU9RnK+ZZqbhrbE853TkLrgodz6kiWMgrHPhU3Aa4Y1ZK66UrkQqhXHdfpRLnbDiXxG6FrgBFfi2kLnuIAp+NqRiVQVKXV6P4j6+QQg7bK3UXLynmcTv5bj7Zj0MpabKp8Re2WQgWZgOapMropb/E5k5BKR3U7sTbSj/cfTCaJOOaPnqDGWgPZrKy83dpY/t99YyBJe6Bd3YL6edH32GPJ+jcYcSfd1q05dyr9Ck86Y4bNcuNMH3XJYpeg2Vml2Qd1iyqNUvoVMQgqOx713GfHCor+pHBMRQpGjO0ZUuqEdEN4ovqz6l
  template:
    metadata:
      name: telegram-secret
      namespace: default
